spring.application.name=cams-api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Auth Service
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CAMS-AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# Customer Service
spring.cloud.gateway.server.webmvc.routes[1].id=customer-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://CAMS-CUSTOMER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=AddRequestHeader=X-Correlation-ID,{X-Correlation-ID}

# Account Service
spring.cloud.gateway.server.webmvc.routes[2].id=account-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://CAMS-ACCOUNT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=AddRequestHeader=X-Correlation-ID,{X-Correlation-ID}

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n