spring.application.name=cams-api-gateway
spring.application.name=cams-api-gateway
server.port=8080


# =========================================================
# Auth Service
# =========================================================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1


# =========================================================
# Customer Service
# =========================================================

spring.cloud.gateway.server.webmvc.routes[1].id=customer-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[1].filters[1]=AddRequestHeader=X-Correlation-ID,{X-Correlation-ID}


# =========================================================
# Account Service
# =========================================================

spring.cloud.gateway.server.webmvc.routes[2].id=account-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webmvc.routes[2].filters[1]=AddRequestHeader=X-Correlation-ID,{X-Correlation-ID}

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n